name: build
on:
  pull_request: {}
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: write
      actions: write
    env:
      CI: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Set git identity
        run: |-
          docker version
          echo `pwd`
          docker run --rm -u root -v `pwd`:/ws/:delegated  \
          public.ecr.aws/sam/build-nodejs12.x bash -xc "cd /ws/ && find ."
    container:
      image: jsii/superchain
